//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWPADB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Logins()
        {
            this.LoginServers = new HashSet<LoginServers>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Utworzony { get; set; }
        public Nullable<System.DateTime> Zmodyfikowany { get; set; }
        public int Id_Group { get; set; }
        public int Id_Roles { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginServers> LoginServers { get; set; }
    }
}
